"""add is_deleted to links

Revision ID: 202f28c6a592
Revises: 13ef1671f3e5
Create Date: 2026-02-14 14:35:53.496667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202f28c6a592'
down_revision: Union[str, Sequence[str], None] = '13ef1671f3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'is_deleted')
    # ### end Alembic commands ###
