"""add_utm_fields_to_link

Revision ID: 23c980b95413
Revises: a1b2c3d4e5f6
Create Date: 2026-02-20 11:09:46.313649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c980b95413'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('utm_source', sa.String(), nullable=True))
    op.add_column('links', sa.Column('utm_medium', sa.String(), nullable=True))
    op.add_column('links', sa.Column('utm_campaign', sa.String(), nullable=True))
    op.add_column('links', sa.Column('utm_term', sa.String(), nullable=True))
    op.add_column('links', sa.Column('utm_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'utm_content')
    op.drop_column('links', 'utm_term')
    op.drop_column('links', 'utm_campaign')
    op.drop_column('links', 'utm_medium')
    op.drop_column('links', 'utm_source')
    # ### end Alembic commands ###
