"""Add ClickEvent model and track_activity column

Revision ID: 4a43f2a87008
Revises: 202f28c6a592
Create Date: 2026-02-14 14:59:12.593161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a43f2a87008'
down_revision: Union[str, Sequence[str], None] = '202f28c6a592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_id'), 'click_events', ['id'], unique=False)
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    op.create_index(op.f('ix_click_events_timestamp'), 'click_events', ['timestamp'], unique=False)
    op.add_column('links', sa.Column('track_activity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'track_activity')
    op.drop_index(op.f('ix_click_events_timestamp'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_id'), table_name='click_events')
    op.drop_table('click_events')
    # ### end Alembic commands ###
