"""Add_title_tags_redirect_type

Revision ID: 67aa42234b74
Revises: 4a43f2a87008
Create Date: 2026-02-19 23:30:15.812172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67aa42234b74'
down_revision: Union[str, Sequence[str], None] = '4a43f2a87008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('title', sa.String(), nullable=True))
    op.add_column('links', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('links', sa.Column('redirect_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'redirect_type')
    op.drop_column('links', 'tags')
    op.drop_column('links', 'title')
    # ### end Alembic commands ###
