"""Add access control to links

Revision ID: c5ec1cf700af
Revises: d276ea49ed6b
Create Date: 2026-02-13 23:05:02.087773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ec1cf700af'
down_revision: Union[str, Sequence[str], None] = 'd276ea49ed6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('links', sa.Column('require_login', sa.Boolean(), nullable=True))
    op.add_column('links', sa.Column('allowed_emails', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'allowed_emails')
    op.drop_column('links', 'require_login')
    op.drop_column('links', 'password_hash')
    # ### end Alembic commands ###
