"""Add access control fields to User

Revision ID: d276ea49ed6b
Revises: 2d6bb693ed6c
Create Date: 2026-02-12 03:36:10.694829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd276ea49ed6b'
down_revision: Union[str, Sequence[str], None] = '2d6bb693ed6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('request_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'request_status')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
